### PR TITLE
t/21 image styles

### PR DESCRIPTION
**Pull request by oleq**
A response to https://github.com/CKEditor5/ckeditor5.github.io/issues/21#issuecomment-263231136.

### CODE REVIEW

**Comment by Reinmar** [comment]
Why this photo? It's beautiful, but do we want to use a non-related photo here? Do we, perhaps, have more CKEditor oriented ideas?

cc @AnnaTomanek, @wojtekidd, @RyszardB?

This is how it looks now:

image

**Comment by Reinmar** [comment]
@oleq, other than the image choice, I like the styles. I guess that we should move some of them (those which make sense to be generalised there) to ckeditor5-image. Could you handle that?

**Comment by oleq** [comment]
@reinmar The image I used is neutral yet colorful. And mine :P I wouldn't mind if we used something else, though. OTOH its just a sample in a dev preview, nothing permanent, so we shouldn't spend too much time on it.

As for the styles, do you see them as a part of i5? Or is it frozen?

**Comment by Reinmar** [comment]
> As for the styles, do you see them as a part of i5? Or is it frozen?

It's already tagged.

**Comment by Reinmar** [comment]
Maybe our whiteboard :D 

img_1585

**Comment by oleq** [comment]
How about no?

**Comment by fredck** [comment]
The proposed image (I mean, the beautiful photo from Olek, ofc) looks great for me.

**Comment by RyszardB** [comment]
it's ok for me

**Pull request merged**
