### PR TITLE
Prepare sample for v0.2.0 release

### LINKED ISSUE #9: Prepare sample for v0.2.0 release
Requires https://github.com/CKEditor5/ckeditor5.github.io/issues/8.

### PR DESCRIPTION
**Pull request by oleq**
It's a rolling PR where all issues related to v0.2.0 are to be merged because otherwise merging them into master would mean publishing.

So far:
- Includes #8 and #11.

Closes #9.

### CODE REVIEW

**Comment by Reinmar** [comment]
All fine for me. I updated some texts to reflect the changes that we've made in iteration 2 (e.g. the 170 closed tickets).

**Comment by Reinmar** [comment]
I've just realised that I miss one thing – dates next to version numbers in the changelog. Could you add them?

**Comment by oleq** [comment]
@Reinmar please, verify the dates.

**Comment by Reinmar** [comment]
They're fine. I also wanted to use the date when the code was tagged.

**Pull request merged**
